/* MAMO BOAT — MAMO RECORD Phase 1 + 2 */
(()=>{"use strict";if(window.__MAMO_RECORD_V2__)return;window.__MAMO_RECORD_V2__=true;
const AK="mamoboat_v40_personal",RK="mamoboat_record_v1",CAP=50,REWARD=10;let ready=false,active=null,view="pre",ans={conviction:null,cashUrge:null};const seen=new Set();
const day=()=>{try{return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date())}catch(_){return new Date().toISOString().slice(0,10)}};
const read=(k,f)=>{try{return JSON.parse(localStorage.getItem(k)||"null")||f}catch(_){return f}},write=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const id=r=>String(r?.id||[r?.time,r?.raceDate,r?.venueCode||r?.venue,r?.raceNo,r?.stake].filter(v=>v!=null&&v!=="").join(":"));
function state(){const s=read(RK,{version:2,balance:0,ledger:[],reflections:{},postReflections:{},seenRecordIds:[]});s.version=2;s.balance=Math.max(0,+s.balance||0);s.ledger=Array.isArray(s.ledger)?s.ledger:[];s.reflections=s.reflections||{};s.postReflections=s.postReflections||{};s.seenRecordIds=Array.isArray(s.seenRecordIds)?s.seenRecordIds:[];return s}
const earned=s=>s.ledger.filter(x=>x.day===day()&&+x.amount>0).reduce((a,x)=>a+(+x.amount||0),0);
function award(s,rid,type){if(s.ledger.some(x=>x.recordId===rid&&x.type===type))return{amount:0,reason:"already"};const amount=Math.max(0,Math.min(REWARD,CAP-earned(s)));if(amount){s.balance+=amount;s.ledger.push({id:`mr-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,recordId:rid,type,amount,day:day(),at:new Date().toISOString(),balanceAfter:s.balance})}return{amount,reason:amount?"awarded":"daily_cap"}}
function css(){if(document.getElementById("mr2css"))return;const s=document.createElement("style");s.id="mr2css";s.textContent=`#mamoRecordSummary{margin:10px 0 4px;padding:13px 14px;border:1px solid #dce4e5;border-left:5px solid #d2a23b;border-radius:13px;background:#fffdf8;display:flex;align-items:center;justify-content:space-between;gap:12px}#mamoRecordSummary small{display:block;color:#8b6a1d;font-size:8px;font-weight:1000;letter-spacing:.12em}#mamoRecordSummary b{display:block;color:#08233d;font-size:15px}#mamoRecordSummary strong{color:#a77709;font-size:25px}.mr-bg{position:fixed;inset:0;z-index:9999;background:#04141f6b;display:none;align-items:flex-end;justify-content:center}.mr-bg.show{display:flex}.mr-sheet{width:min(100%,560px);background:#fff;border-radius:22px 22px 0 0;padding:18px 16px calc(18px + env(safe-area-inset-bottom))}.mr-top{display:flex;justify-content:space-between;gap:10px}.mr-top small{color:#9a7419;font-size:8px;font-weight:1000}.mr-top h2{margin:3px 0;color:#08233d;font-size:23px}.mr-top p,.mr-foot{color:#718188;font-size:10px;line-height:1.55}.mr-close{border:0;border-radius:50%;width:34px;height:34px}.mr-q{margin-top:17px;padding:13px;border:1px solid #e1e7e8;border-radius:13px;background:#fafcfc}.mr-q>span{display:block;font-size:13px;font-weight:900;margin-bottom:9px}.mr-scale{display:grid;grid-template-columns:repeat(5,1fr);gap:6px}.mr-scale button,.mr-emotions button{min-height:44px;border:1px solid #d7e0e1;border-radius:10px;background:#fff;color:#294a59;font-weight:1000}.mr-scale button.sel{background:#08233d;color:#fff}.mr-label{display:flex;justify-content:space-between;margin-top:6px;color:#829097;font-size:8px}.mr-emotions{display:grid;grid-template-columns:repeat(2,1fr);gap:8px}.mr-emotions button{font-size:12px;padding:10px 5px}.mr-foot{text-align:center;margin-top:12px}.mr-done{text-align:center;padding:22px 8px}.mr-done small{color:#997319;font-weight:1000}.mr-done strong{display:block;color:#a77709;font-size:42px;margin:5px}.mr-done h3{color:#08233d}`;document.head.appendChild(s)}
function sheet(){let b=document.getElementById("mamoRecordSheetBg");if(b)return b;b=document.createElement("div");b.id="mamoRecordSheetBg";b.className="mr-bg";b.innerHTML='<div class="mr-sheet"><div id="mamoRecordSheetBody"></div></div>';b.addEventListener("click",e=>{if(e.target===b)close()});document.body.appendChild(b);return b}
function close(){sheet().classList.remove("show");active=null;view="pre";ans={conviction:null,cashUrge:null}}
function head(r,label,title){return `<div class="mr-top"><div><small>${label}</small><h2>${title}</h2><p>${r?.venue||""} ${r?.raceNo?`${r.raceNo}R / `:""}分析はMAMOがあとでやります。</p></div><button class="mr-close" data-close>×</button></div>`}
function show(r,m){active=r;view=m;ans={conviction:null,cashUrge:null};const body=document.getElementById("mamoRecordSheetBody");body.innerHTML=m==="post"?head(r,"MAMO RECORD / RESULT","結果を見た今は？")+'<div class="mr-q"><span>いちばん近い気持ちを1つだけ</span><div class="mr-emotions"><button data-emotion="satisfied">納得した</button><button data-emotion="frustrated">悔しい</button><button data-emotion="chase">取り返したい</button><button data-emotion="neutral">特になし</button></div></div><div class="mr-foot">1タップで完了。その時の気持ちだけ残します。</div>':head(r,"MAMO RECORD / 2 TAPS","今の気持ちだけ、残す。")+`<div class="mr-q"><span>この勝負、どれくらい納得してる？</span><div class="mr-scale" data-group="conviction">${[1,2,3,4,5].map(n=>`<button data-answer="${n}">${n}</button>`).join("")}</div><div class="mr-label"><i>なんとなく</i><i>かなり納得</i></div></div><div class="mr-q"><span>現金で買いたい気持ちは？</span><div class="mr-scale" data-group="cashUrge">${[1,2,3,4,5].map(n=>`<button data-answer="${n}">${n}</button>`).join("")}</div><div class="mr-label"><i>ほぼない</i><i>かなり強い</i></div></div><div class="mr-foot">2つ選ぶと自動完了。BET額・勝敗ではRECORDは増えません。</div>`;sheet().classList.add("show")}
function track(name,p,r){const a=window.MAMO_DECISION_EVENTS;try{(a?.track||a?.send)?.(name,p,{screen:"race",raceDate:r?.raceDate||null,venueCode:r?.venueCode||null,raceNo:r?.raceNo||null})}catch(_){}}
function done(a){document.getElementById("mamoRecordSheetBody").innerHTML=`<div class="mr-done"><small>RECORD COMPLETE</small><strong>${a.amount?`+${a.amount}R`:"記録済み"}</strong><h3>${a.reason==="daily_cap"?"今日の上限に到達":"あとはMAMOがまとめます。"}</h3></div>`;summary();setTimeout(close,1150)}
function pre(){if(!active||ans.conviction==null||ans.cashUrge==null)return;const rid=id(active),s=state();s.reflections[rid]={recordId:rid,conviction:+ans.conviction,cashUrge:+ans.cashUrge,recordedAt:new Date().toISOString(),raceDate:active.raceDate||null,venueCode:active.venueCode||null,raceNo:active.raceNo||null};const a=award(s,rid,"reflection_complete");write(RK,s);track("mamo_record_reflection_completed",{record_id:rid,conviction:+ans.conviction,cash_urge:+ans.cashUrge,record_awarded:a.amount},active);done(a)}
function post(emotion){if(!active)return;const rid=id(active),s=state();if(s.postReflections[rid])return done({amount:0,reason:"already"});s.postReflections[rid]={recordId:rid,emotion,recordedAt:new Date().toISOString(),status:active.status||null};const a=award(s,rid,"result_reflection_complete");write(RK,s);track("mamo_record_result_reflection_completed",{record_id:rid,emotion,status:active.status||null,record_awarded:a.amount},active);done(a)}
function click(e){if(e.target.closest("[data-close]"))return close();const em=e.target.closest("[data-emotion]");if(em&&view==="post")return post(em.dataset.emotion);const b=e.target.closest("[data-answer]");if(!b||view!=="pre")return;const g=b.closest("[data-group]")?.dataset.group;if(!g)return;ans[g]=+b.dataset.answer;b.parentElement.querySelectorAll("button").forEach(x=>x.classList.toggle("sel",x===b));if(ans.conviction!=null&&ans.cashUrge!=null)setTimeout(pre,150)}
function summary(){const h=document.getElementById("home"),stats=h?.querySelector(".three-stats");if(!stats)return;let p=document.getElementById("mamoRecordSummary");if(!p){p=document.createElement("div");p.id="mamoRecordSummary";stats.insertAdjacentElement("afterend",p)}const s=state();p.innerHTML=`<div><small>MAMO RECORD</small><b>気持ちを残すほど、分析の材料が増える。</b><span style="font-size:8px;color:#7c8a90">今日 ${earned(s)}/${CAP}R</span></div><strong>${s.balance.toLocaleString("ja-JP")}R</strong>`}
function scan(){const records=Array.isArray(read(AK,{}).records)?read(AK,{}).records:[],s=state(),persist=new Set(s.seenRecordIds);if(!ready){records.forEach(r=>{const rid=id(r);if(rid){seen.add(rid);persist.add(rid)}});s.seenRecordIds=[...persist].slice(-3000);write(RK,s);ready=true}else{for(const r of records){const rid=id(r);if(!rid||seen.has(rid)||persist.has(rid))continue;seen.add(rid);persist.add(rid);s.seenRecordIds=[...persist].slice(-3000);write(RK,s);if(!s.reflections[rid])setTimeout(()=>{if(!active)show(r,"pre")},250);break}}if(active)return;const now=state(),candidate=[...records].reverse().find(r=>{const rid=id(r);return rid&&now.reflections[rid]&&!now.postReflections[rid]&&(r.settled===true||r.resultEventAt||["won","lost","refunded"].includes(String(r.status||"").toLowerCase()))});if(candidate)setTimeout(()=>{if(!active)show(candidate,"post")},300)}
function boot(){css();sheet();sheet().addEventListener("click",click);summary();scan();setInterval(scan,1000);window.addEventListener("pageshow",()=>{summary();scan()});window.MAMO_RECORD=Object.freeze({version:2,balance:()=>state().balance,state,dailyCap:CAP})}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();})();
