/* MAMO BOAT Race UX v1 — mobile-first rail, tabs and horizontal swipe without touching betting logic. */
(() => {
  "use strict";
  if (window.__MAMO_RACE_UX_V1__) return;
  window.__MAMO_RACE_UX_V1__ = true;
  const STATE_KEY = "mamoboat_v40_personal";
  let touchStart = null;
  let lastKey = "";
  const readState = () => { try { return JSON.parse(localStorage.getItem(STATE_KEY)) || {}; } catch (_) { return {}; } };
  const txt = el => (el?.textContent || "").replace(/\s+/g," ").trim();
  const root = () => document.getElementById("raceView");
  const activeRace = () => Number(readState().raceNo) || Number((document.querySelector(".racechip.active,.race-chip.active,[aria-current='true']")?.textContent||"").match(/\d+/)?.[0]) || 1;
  function clickMatching(patterns){const r=root()||document;const all=[...r.querySelectorAll("button,a,[role='button']")];const el=all.find(x=>patterns.some(re=>re.test(txt(x))));if(el){el.click();return true}return false}
  function goRace(n){if(n<1||n>12)return false;const ok=clickMatching([new RegExp(`^${n}(R|レース)?$`,`i`),new RegExp(`^${n}$`)]);if(ok)setTimeout(sync,80);return ok}
  function scrollToAir(){const r=root();if(!r)return;const candidates=[...r.querySelectorAll("button,h1,h2,h3,h4,div,section")].filter(el=>/AIR BET/i.test(txt(el)));const target=candidates[0];if(target)target.scrollIntoView({behavior:"smooth",block:"center"})}
  function clickTab(label){const map={entries:[/出走表/,/レーサー/,/選手/],odds:[/オッズ/],before:[/直前/],result:[/結果/]};return clickMatching(map[label]||[])}
  function ensureShell(){const r=root();const raceScreen=document.getElementById("race");if(!r||!raceScreen?.classList.contains("active"))return null;let shell=document.getElementById("mamoRaceUx");if(!shell){shell=document.createElement("div");shell.id="mamoRaceUx";shell.className="mru-shell";r.insertAdjacentElement("beforebegin",shell);shell.innerHTML=`<div class="mru-head"><div><small>RACE CONTROL</small><strong id="mruCurrent">1R</strong></div><span>左右スワイプで前後R</span></div><div class="mru-races" aria-label="レース切替"></div><div class="mru-tabs"><button data-tab="entries">出走表</button><button data-tab="odds">オッズ</button><button data-tab="before">直前</button><button data-tab="result">結果</button></div><div class="mru-actions"><button data-action="air">AIR BET</button><button data-action="live">LIVE</button><button data-action="official">公式</button><button data-action="real">REAL</button></div>`;const rail=shell.querySelector(".mru-races");for(let i=1;i<=12;i++){const b=document.createElement("button");b.type="button";b.dataset.race=String(i);b.textContent=`${i}R`;b.onclick=()=>goRace(i);rail.appendChild(b)}shell.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>clickTab(b.dataset.tab));shell.querySelector("[data-action='air']").onclick=scrollToAir;shell.querySelector("[data-action='live']").onclick=()=>clickMatching([/LIVE/i,/ライブ/,/レース映像/]);shell.querySelector("[data-action='official']").onclick=()=>clickMatching([/BOAT RACE公式/,/公式サイト/]);shell.querySelector("[data-action='real']").onclick=()=>clickMatching([/REAL投票/]);}return shell}
  function sync(){const shell=ensureShell();if(!shell)return;const n=activeRace();shell.querySelector("#mruCurrent").textContent=`${n}R`;shell.querySelectorAll("[data-race]").forEach(b=>b.classList.toggle("active",Number(b.dataset.race)===n));const active=shell.querySelector(`[data-race='${n}']`);active?.scrollIntoView({behavior:"smooth",inline:"center",block:"nearest"});const key=`${readState().venue||""}:${n}`;if(key!==lastKey){lastKey=key;shell.animate?.([{opacity:.6},{opacity:1}],{duration:180})}}
  function bindSwipe(){const r=root();if(!r||r.dataset.mamoSwipeBound==="1")return;r.dataset.mamoSwipeBound="1";r.addEventListener("touchstart",e=>{const t=e.touches?.[0];if(!t)return;touchStart={x:t.clientX,y:t.clientY,time:Date.now()}},{passive:true});r.addEventListener("touchend",e=>{if(!touchStart)return;const t=e.changedTouches?.[0];if(!t){touchStart=null;return}const dx=t.clientX-touchStart.x,dy=t.clientY-touchStart.y,dt=Date.now()-touchStart.time;touchStart=null;if(dt>700||Math.abs(dx)<65||Math.abs(dx)<Math.abs(dy)*1.3)return;const n=activeRace();if(dx<0&&n<12)goRace(n+1);else if(dx>0&&n>1)goRace(n-1)},{passive:true})}
  function style(){if(document.getElementById("mruStyle"))return;const s=document.createElement("style");s.id="mruStyle";s.textContent=`.mru-shell{position:sticky;top:0;z-index:40;background:rgba(255,255,255,.98);border-bottom:1px solid var(--soft-line,#dbe4e5);padding:8px 8px 10px;box-shadow:0 3px 10px rgba(7,27,43,.08)}.mru-head{display:flex;align-items:end;justify-content:space-between;gap:8px}.mru-head small{display:block;font-size:7px;font-weight:1000;letter-spacing:.12em;color:var(--teal-dark,#007c78)}.mru-head strong{font-size:22px}.mru-head span{font-size:8px;color:var(--muted,#697a80);font-weight:800}.mru-races{display:flex;gap:5px;overflow-x:auto;scrollbar-width:none;padding:7px 0 5px}.mru-races::-webkit-scrollbar{display:none}.mru-races button{flex:0 0 auto;min-width:42px;height:34px;border:1px solid #ccd8d9;background:#f6f9f9;color:#071b2b;font-weight:1000;border-radius:4px}.mru-races button.active{background:#071b2b;color:#fff;border-color:#071b2b}.mru-tabs{display:grid;grid-template-columns:repeat(4,1fr);gap:4px}.mru-tabs button{min-height:34px;border:1px solid #d5dfe0;background:#fff;color:#071b2b;font-size:10px;font-weight:1000}.mru-actions{display:grid;grid-template-columns:1.4fr 1fr 1fr 1fr;gap:4px;margin-top:5px}.mru-actions button{min-height:38px;border:0;font-size:9px;font-weight:1000}.mru-actions [data-action='air']{background:#00a8a0;color:#fff}.mru-actions [data-action='live']{background:#fff;border:1px solid #00a8a0;color:#007c78}.mru-actions [data-action='official']{background:#f2f5f5;color:#071b2b}.mru-actions [data-action='real']{background:#071b2b;color:#fff}@media(min-width:760px){.mru-shell{position:relative;top:auto;border:1px solid var(--soft-line,#dbe4e5);margin-bottom:10px}.mru-actions button{font-size:10px}}`;document.head.appendChild(s)}
  function boot(){style();setInterval(()=>{sync();bindSwipe()},700)}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();
