/* MAMO BOAT — MAMO STORY mobile reader */
(()=>{"use strict";if(window.__MAMO_STORY__)return;window.__MAMO_STORY__=true;
let IMG="";
const PAGES=[
  [0,0,"01–02","好きだからこそ、つい参加する。"],
  [1,0,"03–04","モヤモヤの正体を、まず知る。"],
  [0,1,"05–06","AIR BETで、もし賭けていたらを残す。"],
  [1,1,"07–08","数字と気持ちを、あとから見る。"],
  [0,2,"09–10","答えをもらうより、自分で気づく。"],
  [1,2,"11–12","なんとなく100円を、見送れる日が来る。"],
  [0,3,"13–14","勝つ日も負ける日も、自分の型が残る。"],
  [1,3,"15–16","勝負の主導権を、自分に。"],
];
function css(){if(document.getElementById("mamoStoryStyle"))return;const s=document.createElement("style");s.id="mamoStoryStyle";s.textContent=`
#mamoStoryTeaser{margin:14px 0 18px;border:1px solid #d8e0e3;border-left:6px solid #d3a637;border-radius:16px;background:linear-gradient(135deg,#fffdf8,#f7fbfc);box-shadow:0 9px 24px rgba(6,35,58,.08);overflow:hidden}
#mamoStoryTeaser button{width:100%;border:0;background:transparent;padding:15px 16px;text-align:left;color:#08233d;display:flex;align-items:center;gap:13px}
#mamoStoryTeaser .story-mark{width:48px;height:48px;flex:0 0 48px;border-radius:50%;display:grid;place-items:center;background:#08233d;color:#fff;font-weight:1000;font-size:20px}
#mamoStoryTeaser small{display:block;color:#9a7419;font-size:9px;font-weight:1000;letter-spacing:.11em;margin-bottom:3px}
#mamoStoryTeaser strong{display:block;font-size:18px;line-height:1.25}.story-arrow{margin-left:auto;font-size:24px;color:#0a9fa8}
#mamoStoryOverlay{position:fixed;inset:0;z-index:12000;background:#eef2f4;display:none;overflow:hidden;color:#08233d}#mamoStoryOverlay.open{display:block}
.story-shell{height:100%;display:flex;flex-direction:column}.story-head{position:relative;z-index:3;display:flex;align-items:center;justify-content:space-between;gap:12px;padding:calc(10px + env(safe-area-inset-top)) 14px 10px;background:rgba(255,255,255,.96);border-bottom:1px solid #d8e0e3}.story-head small{display:block;color:#9a7419;font-size:8px;font-weight:1000;letter-spacing:.13em}.story-head b{font-size:17px}.story-close{width:40px;height:40px;border:0;border-radius:50%;background:#edf0f2;color:#08233d;font-size:22px}
.story-scroll{flex:1;overflow-y:auto;-webkit-overflow-scrolling:touch;padding:14px 12px calc(125px + env(safe-area-inset-bottom));scroll-behavior:smooth}.story-intro{padding:7px 5px 14px}.story-intro h2{margin:0 0 6px;font-size:28px;line-height:1.16}.story-intro h2 span{color:#0aa8ad}.story-intro p{margin:0;color:#647782;font-size:12px;line-height:1.65}.story-page{margin:0 0 16px;background:#fff;border:1px solid #d9dfe1;border-radius:15px;box-shadow:0 8px 18px rgba(6,35,58,.07);overflow:hidden}.story-crop{width:100%;aspect-ratio:4/3;background-image:var(--mamo-story-img,none);background-repeat:no-repeat;background-size:200% 400%;background-color:#eee}.story-meta{padding:10px 12px 12px;display:flex;gap:10px;align-items:flex-start}.story-no{flex:0 0 auto;color:#a57916;font-size:9px;font-weight:1000;letter-spacing:.1em}.story-copy{font-size:13px;font-weight:900;line-height:1.45}.story-end{margin-top:20px;padding:24px 18px 22px;border-radius:17px;background:#08233d;color:#fff;text-align:center}.story-end small{color:#dcb655;font-size:9px;font-weight:1000;letter-spacing:.14em}.story-end h2{margin:8px 0 7px;font-size:30px;line-height:1.2}.story-end p{margin:0;color:#cbd9df;font-size:11px;line-height:1.65}.story-cta{position:fixed;z-index:4;left:12px;right:12px;bottom:calc(12px + env(safe-area-inset-bottom));display:flex;gap:8px}.story-cta button{min-height:54px;border-radius:13px;font-weight:1000;font-size:15px;box-shadow:0 8px 20px rgba(6,35,58,.18)}.story-back{flex:0 0 88px;border:1px solid #a9b8be;background:#fff;color:#08233d}.story-air{flex:1;border:0;background:#08adb6;color:#fff}.story-img-error{display:none;padding:20px;color:#6f7e86;text-align:center;background:#fff5f2}.story-img-error.show{display:block}
body.mamo-story-open{overflow:hidden!important}
@media(min-width:650px){#mamoStoryOverlay{left:50%;right:auto;width:min(620px,100%);transform:translateX(-50%);box-shadow:0 0 40px rgba(0,0,0,.25)}}
`;document.head.appendChild(s)}
async function loadImage(){try{const r=await fetch("mamo-story-image.txt?v=20260822-1",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);const b64=(await r.text()).trim();if(!b64)throw new Error("empty image");IMG=`data:image/jpeg;base64,${b64}`;document.documentElement.style.setProperty("--mamo-story-img",`url("${IMG}")`);document.getElementById("mamoStoryError")?.classList.remove("show");return true}catch(e){console.warn("MAMO STORY image load failed",e);document.getElementById("mamoStoryError")?.classList.add("show");return false}}
function pos(x,y){const px=x?"100%":"0%";const py=["0%","33.333%","66.666%","100%"][y];return `${px} ${py}`}
function overlay(){let o=document.getElementById("mamoStoryOverlay");if(o)return o;o=document.createElement("div");o.id="mamoStoryOverlay";o.innerHTML=`<div class="story-shell"><header class="story-head"><div><small>MAMO STORY / READ FIRST</small><b>3分でわかる MAMO BOAT</b></div><button class="story-close" type="button" aria-label="閉じる">×</button></header><main class="story-scroll"><div class="story-intro"><h2>勝つ方法ではなく、<br><span>自分の勝負を知る話。</span></h2><p>記録して、あとから見る。それだけで「なんとなく」が少しずつ見えるようになる。</p></div><div id="mamoStoryPages"></div><div class="story-img-error" id="mamoStoryError">漫画画像を読み込めませんでした。再読み込みしてください。</div><div class="story-end"><small>MAMO BOAT</small><h2>勝負の主導権を、<br>自分に。</h2><p>予想を当てるためではなく、自分がどんな時に勝負を選ぶのかを知るために。</p></div></main><div class="story-cta"><button class="story-back" type="button">閉じる</button><button class="story-air" type="button">AIR BETを体験する →</button></div></div>`;document.body.appendChild(o);const box=o.querySelector("#mamoStoryPages");box.innerHTML=PAGES.map(([x,y,no,copy])=>`<article class="story-page"><div class="story-crop" style="background-position:${pos(x,y)}"></div><div class="story-meta"><span class="story-no">${no}</span><span class="story-copy">${copy}</span></div></article>`).join("");o.querySelectorAll(".story-close,.story-back").forEach(b=>b.addEventListener("click",close));o.querySelector(".story-air").addEventListener("click",()=>{close();try{window.MAMO_DECISION_EVENTS?.track?.("mamo_story_airbet_cta",{source:"story"},{screen:"story"})}catch(_){ }if(typeof window.go==="function")window.go("venues");setTimeout(()=>window.scrollTo({top:0,behavior:"smooth"}),80)});return o}
async function open(){const o=overlay();o.classList.add("open");document.body.classList.add("mamo-story-open");o.querySelector(".story-scroll").scrollTop=0;if(!IMG)await loadImage();try{window.MAMO_DECISION_EVENTS?.track?.("mamo_story_opened",{version:1},{screen:"story"})}catch(_){}}
function close(){document.getElementById("mamoStoryOverlay")?.classList.remove("open");document.body.classList.remove("mamo-story-open")}
function teaser(){const home=document.getElementById("home");if(!home||document.getElementById("mamoStoryTeaser"))return;const t=document.createElement("div");t.id="mamoStoryTeaser";t.innerHTML=`<button type="button"><span class="story-mark">読</span><span><small>MAMO STORY</small><strong>漫画でわかる「勝負の主導権」</strong></span><span class="story-arrow">›</span></button>`;t.querySelector("button").addEventListener("click",open);const record=document.getElementById("mamoRecordHero")||document.getElementById("mamoRecordSummary");const title=home.querySelector(".home-titlebar");if(record)record.insertAdjacentElement("afterend",t);else if(title)title.insertAdjacentElement("beforebegin",t);else home.prepend(t)}
function boot(){css();overlay();teaser();loadImage();setTimeout(teaser,500);setTimeout(teaser,1600);window.addEventListener("pageshow",teaser);window.MAMO_STORY=Object.freeze({open,close})}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot()})();