/* MAMO BOAT Service Worker refresh v35 — load the extracted pressroom membership module. */
(()=>{
  "use strict";
  const currentJstLabel=()=>{const parts=Object.fromEntries(new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()).map(p=>[p.type,p.value]));const y=Number(parts.year),m=Number(parts.month),d=Number(parts.day);const weekday=["SUN","MON","TUE","WED","THU","FRI","SAT"][new Date(Date.UTC(y,m-1,d)).getUTCDay()];return `${parts.year}.${parts.month}.${parts.day} ${weekday}`;};
  const installPlanCollapseFix=()=>{if(document.getElementById("mamoPlanCollapseFix"))return;const style=document.createElement("style");style.id="mamoPlanCollapseFix";style.textContent=`html.mamo-insights-v2 #mamoDecisionPanel,html.mamo-insights-v2 #mamoBaselinePanel,html.mamo-insights-v2 #mamoTriggerPanel,html.mamo-insights-v2 #mamoPeriodTriggerSummary,html.mamo-insights-v2 #mamoBehaviorPatternProfile,html.mamo-insights-v2 #mamoCompoundPatternPanel,html.mamo-insights-v2 #mamoDecisionStateScore,html.mamo-insights-v2 #mamoRecordEditorial,html.mamo-insights-v2 #goldEditorialDesk{display:none!important}body:not([data-mamo-plan="gold"]) #mamoPressIntel{display:none!important}`;document.head.appendChild(style);};
  const installBetModalBackButton=()=>{if(!document.getElementById("mamoBetModalBackStyle")){const style=document.createElement("style");style.id="mamoBetModalBackStyle";style.textContent=`.mamo-bet-modal-back{display:inline-flex;align-items:center;gap:6px;margin:0 0 14px;padding:8px 12px;border:1px solid #cfd9e1;border-radius:999px;background:#fff;color:#08233d;font:900 14px/1 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;box-shadow:0 2px 7px rgba(8,35,61,.06);cursor:pointer}.mamo-bet-modal-back:active{transform:translateY(1px);background:#f5f8fa}`;document.head.appendChild(style);}const sync=()=>{const bg=document.getElementById("modalBg");if(!bg?.classList.contains("show"))return;const modal=bg.querySelector(".modal");if(!modal||modal.querySelector(".mamo-bet-modal-back"))return;const text=modal.textContent||"";if(!text.includes("購入内容")||!text.includes("AIR BETを確定する"))return;const button=document.createElement("button");button.type="button";button.className="mamo-bet-modal-back";button.textContent="← 戻る";button.setAttribute("aria-label","購入確認を閉じてレース画面へ戻る");button.addEventListener("click",()=>window.closeModal?.());modal.prepend(button);};sync();const root=document.getElementById("modalBg")||document.body;const observer=new MutationObserver(sync);observer.observe(root,{subtree:true,childList:true,attributes:true,attributeFilter:["class"]});};
  const clearStaleStoryState=(force=false)=>{const overlay=document.getElementById("mamoStoryOverlay");const validOpen=!force&&document.body?.classList.contains("mamo-story-open")&&overlay?.dataset.mamoStoryOpen==="true"&&overlay.isConnected;if(validOpen)return;if(overlay){overlay.dataset.mamoStoryOpen="false";overlay.setAttribute("aria-hidden","true");overlay.style.pointerEvents="none";overlay.replaceChildren();overlay.remove();}document.documentElement.classList.remove("mamo-story-session");document.body?.classList.remove("mamo-story-open","mamo-story-session");};
  const syncHomeToday=()=>{const date=document.getElementById("homeDateText");if(date)date.textContent=currentJstLabel();};
  const loadMamokamo=()=>{if(document.querySelector('script[data-mamo-mamokamo="1"]'))return;const script=document.createElement("script");script.src="mamokamo.js?v=20260823-4";script.async=true;script.dataset.mamoMamokamo="1";document.head.appendChild(script);};
  const loadMamoStory=()=>{if(document.querySelector('script[data-mamo-story="1"]'))return;const script=document.createElement("script");script.src="mamo-story.js?v=20260830-4";script.async=true;script.dataset.mamoStory="1";document.head.appendChild(script);};
  const register=async()=>{installPlanCollapseFix();installBetModalBackButton();clearStaleStoryState();syncHomeToday();[250,800,1800,4000].forEach(ms=>setTimeout(syncHomeToday,ms));setInterval(syncHomeToday,60000);window.addEventListener("pageshow",event=>{installPlanCollapseFix();clearStaleStoryState(event.persisted===true);syncHomeToday();});loadMamokamo();loadMamoStory();if(!("serviceWorker" in navigator))return;try{const reg=await navigator.serviceWorker.register("./sw.js",{scope:"./",updateViaCache:"none"});const refresh=()=>reg.update().catch(()=>{});if("requestIdleCallback" in window)requestIdleCallback(refresh,{timeout:4000});else setTimeout(refresh,2500);}catch(e){console.warn("MAMO SW refresh failed",e)}};
  installPlanCollapseFix();clearStaleStoryState();loadMamoStory();if(document.readyState==="complete")register();else window.addEventListener("load",register,{once:true});
})();
