/* MAMO BOAT Voice Control v1 — push-to-talk + shared command executor. */
(() => {
  "use strict";
  if (window.__MAMO_VOICE_V1__) return;
  window.__MAMO_VOICE_V1__ = true;
  const SpeechRecognition=window.SpeechRecognition||window.webkitSpeechRecognition;let recognition=null,listening=false;
  const norm=s=>String(s||"").replace(/\s+/g,"").replace(/[０-９]/g,c=>String.fromCharCode(c.charCodeAt(0)-0xFEE0));
  const textOf=el=>(el?.textContent||"").replace(/\s+/g," ").trim();
  const clickByText=(patterns,root=document)=>{const items=[...root.querySelectorAll("button,a,[role='button']")];const found=items.find(el=>patterns.some(re=>re.test(textOf(el))));if(found){found.click();return true}return false};
  const raceRoot=()=>document.getElementById("raceView")||document;
  const parseRace=t=>{const m=norm(t).replace(/レース/g,"R").match(/(?:^|[^0-9])([1-9]|1[0-2])R?/i);return m?Number(m[1]):null};
  const parseAmount=t=>{const m=norm(t).replace(/円|ビー|B/gi,"").match(/(?:賭け|ベット|bet|投票|で)?([0-9]{2,6})(?:だけ)?/i);return m?Number(m[1]):null};
  function confirmReal(onYes){let m=document.getElementById("mamoVoiceConfirm");if(!m){m=document.createElement("div");m.id="mamoVoiceConfirm";m.className="mvc-confirm";document.body.appendChild(m)}m.innerHTML=`<div><p>REAL投票サイトを開きますか？</p><span><button data-no>キャンセル</button><button data-yes>開く</button></span></div>`;m.classList.add("show");m.querySelector("[data-no]").onclick=()=>m.classList.remove("show");m.querySelector("[data-yes]").onclick=()=>{m.classList.remove("show");onYes?.()}}
  function executeCommand(raw){const t=String(raw||""),s=norm(t);if(/次(の)?レース|次R/i.test(s)){const c=Number((document.querySelector(".racechip.active,.race-chip.active,[aria-current='true']")?.textContent||"").match(/\d+/)?.[0]);return c&&c<12&&clickByText([new RegExp(`^${c+1}(R|レース)?$`)],raceRoot())?{ok:true,message:`${c+1}Rへ移動します。`}:{ok:false,message:"次のレースを特定できませんでした。"}}if(/前(の)?レース|前R/i.test(s)){const c=Number((document.querySelector(".racechip.active,.race-chip.active,[aria-current='true']")?.textContent||"").match(/\d+/)?.[0]);return c>1&&clickByText([new RegExp(`^${c-1}(R|レース)?$`)],raceRoot())?{ok:true,message:`${c-1}Rへ移動します。`}:{ok:false,message:"前のレースを特定できませんでした。"}}const rn=parseRace(t);if(rn&&/レース|R|開いて|見せて/.test(t)&&clickByText([new RegExp(`^${rn}(R|レース)?$`)],raceRoot()))return{ok:true,message:`${rn}Rへ移動します。`};if(/オッズ/.test(s)&&clickByText([/オッズ/],raceRoot()))return{ok:true,message:"オッズを開きます。"};if(/ライブ|LIVE|映像/i.test(s)&&clickByText([/LIVE/i,/ライブ/,/レース映像/],raceRoot()))return{ok:true,message:"LIVEを開きます。"};if(/公式/.test(s)&&clickByText([/BOAT RACE公式/,/公式サイト/],raceRoot()))return{ok:true,message:"BOAT RACE公式を開きます。"};if(/リアル|REAL|実投票/i.test(s)){confirmReal(()=>clickByText([/REAL投票/],raceRoot()));return{ok:true,message:"REAL投票への移動を確認します。"}}if(/編集部|新聞|朝刊|週間|月刊/.test(s)){if(typeof window.go==="function")window.go("analysis");setTimeout(()=>{if(/週間/.test(s))clickByText([/週間/]);if(/月刊/.test(s))clickByText([/月刊/]);if(/朝刊/.test(s))clickByText([/朝刊/])},80);return{ok:true,message:"編集部を開きます。"}}if(/記録/.test(s)&&typeof window.go==="function"){window.go("records");return{ok:true,message:"記録を開きます。"}}if(/ホーム|開催一覧/.test(s)&&typeof window.go==="function"){window.go("home");return{ok:true,message:"ホームへ戻ります。"}}const amount=parseAmount(t);if(amount&&/AIR|エア|ベット|賭け/i.test(t)){const inputs=[...document.querySelectorAll("input")].filter(i=>/number|text/.test(i.type||"text"));const input=inputs.find(i=>/B|金額|BET|ベット|stake/i.test(`${i.placeholder||""} ${i.name||""} ${i.id||""} ${i.getAttribute("aria-label")||""}`))||inputs.find(i=>i.type==="number");if(input){input.focus();input.value=String(amount);input.dispatchEvent(new Event("input",{bubbles:true}));input.dispatchEvent(new Event("change",{bubbles:true}));return{ok:true,message:`AIR BET金額に${amount.toLocaleString("ja-JP")}Bを入力しました。画面で確認してください。`}}if(/今日はここまで|終了|やめる/.test(s)){localStorage.setItem("mamoboat_voice_last_stop",new Date().toISOString());return{ok:true,message:"今日はここまで、と記録しました。"}}return{ok:false,message:"コマンドを認識できませんでした。"}}
  window.MAMOVoiceExecute=executeCommand;
  function setStatus(text,error=false){const el=document.getElementById("mamoVoiceStatus");if(el){el.textContent=text;el.dataset.error=error?"1":"0"}}
  function startVoice(){if(!SpeechRecognition){setStatus("このブラウザでは音声認識を利用できません。",true);return}if(listening){try{recognition.stop()}catch(_){}return}recognition=new SpeechRecognition();recognition.lang="ja-JP";recognition.interimResults=false;recognition.continuous=false;recognition.onstart=()=>{listening=true;document.getElementById("mamoVoiceBtn")?.classList.add("listening");setStatus("聞いています…")};recognition.onresult=e=>{const t=e.results?.[0]?.[0]?.transcript||"";const r=executeCommand(t);setStatus(r.message,!r.ok)};recognition.onerror=e=>setStatus(e.error==="not-allowed"?"マイクの利用が許可されていません。":"音声を認識できませんでした。",true);recognition.onend=()=>{listening=false;document.getElementById("mamoVoiceBtn")?.classList.remove("listening")};try{recognition.start()}catch(_){setStatus("音声認識を開始できませんでした。",true)}}
  function render(){if(document.getElementById("mamoVoiceDock"))return;const d=document.createElement("div");d.id="mamoVoiceDock";d.className="mamo-voice-dock";d.innerHTML=`<button id="mamoVoiceBtn" type="button">🎙<small>VOICE</small></button><div id="mamoVoiceStatus">押して話す / Hey MAMO設定あり</div>`;document.body.appendChild(d);d.querySelector("#mamoVoiceBtn").onclick=startVoice}
  function styles(){if(document.getElementById("mamoVoiceStyle"))return;const s=document.createElement("style");s.id="mamoVoiceStyle";s.textContent=`.mamo-voice-dock{position:fixed;right:10px;bottom:76px;z-index:9996;display:flex;align-items:center;gap:7px;background:rgba(7,27,43,.94);padding:7px;border-radius:24px;box-shadow:0 5px 18px rgba(0,0,0,.22);max-width:calc(100vw - 20px)}#mamoVoiceBtn{width:46px;height:46px;border-radius:50%;border:0;background:#00a8a0;color:#fff;font-size:20px;font-weight:1000}#mamoVoiceBtn small{display:block;font-size:6px}#mamoVoiceBtn.listening{animation:mvcPulse 1s infinite}#mamoVoiceStatus{max-width:190px;color:#fff;font-size:9px;font-weight:800}.mvc-confirm{display:none;position:fixed;inset:0;z-index:9999;background:rgba(0,0,0,.48);align-items:center;justify-content:center;padding:18px}.mvc-confirm.show{display:flex}.mvc-confirm>div{width:min(420px,100%);background:#fff;padding:18px}.mvc-confirm span{display:grid;grid-template-columns:1fr 1fr;gap:8px}.mvc-confirm button{min-height:42px;font-weight:900}.mvc-confirm [data-yes]{background:#071b2b;color:#fff;border:0}@keyframes mvcPulse{50%{transform:scale(1.12)}}`;document.head.appendChild(s)}
  function boot(){styles();render()}if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",boot,{once:true});else boot();
})();