import { LipEngine } from "./lip-engine.js";

const $=id=>document.getElementById(id),video=$("camera"),canvas=$("overlay"),engineStatus=$("engineStatus"),startCamera=$("startCamera"),stopCamera=$("stopCamera"),cameraPlaceholder=$("cameraPlaceholder"),cameraHint=$("cameraHint"),calibrationCount=$("calibrationCount"),calibrationFill=$("calibrationFill"),calibrationPromptNumber=$("calibrationPromptNumber"),calibrationPromptText=$("calibrationPromptText"),calibrationCapture=$("calibrationCapture"),calibrationPrev=$("calibrationPrev"),calibrationNext=$("calibrationNext"),calibrationReset=$("calibrationReset"),calibrationProfile=$("calibrationProfile"),calibrationPromptList=$("calibrationPromptList"),trainingPhrase=$("trainingPhrase"),customPhrase=$("customPhrase"),addPhrase=$("addPhrase"),trainButton=$("trainButton"),recognizeButton=$("recognizeButton"),recordingBadge=$("recordingBadge"),trainingCount=$("trainingCount"),phraseProgress=$("phraseProgress"),clearTraining=$("clearTraining"),candidateList=$("candidateList"),recognitionEmpty=$("recognitionEmpty"),conversationText=$("conversationText"),undoConversation=$("undoConversation"),addPeriod=$("addPeriod"),clearConversation=$("clearConversation"),speakConversation=$("speakConversation"),freeText=$("freeText"),speakText=$("speakText"),stopSpeak=$("stopSpeak");
let cameraStarted=false,engineReady=false,busy=false,conversationHistory=[],calibrationIndex=0;
const setStatus=text=>engineStatus.textContent=text,sleep=ms=>new Promise(r=>setTimeout(r,ms));
const engine=new LipEngine({video,canvas,onStatus:setStatus,onFrame:({hasFace})=>{if(!cameraStarted||busy)return;cameraHint.textContent=hasFace?"顔を検出しています。口元の線が表示されれば準備OKです。":"顔が見つかりません。正面を向き、明るい場所で試してください。"}});
function speak(text){const value=String(text||"").trim();if(!value)return;if(!("speechSynthesis" in window)){alert("このブラウザでは音声読み上げを利用できません。");return}speechSynthesis.cancel();const utterance=new SpeechSynthesisUtterance(value);utterance.lang="ja-JP";utterance.rate=.92;speechSynthesis.speak(utterance)}
function escapeHtml(str){return String(str).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
const shortLabel=phrase=>phrase.length<=10?phrase:`${phrase.slice(0,9)}…`;
function renderPhraseOptions(selected=trainingPhrase.value){const phrases=engine.phrases();trainingPhrase.innerHTML=phrases.map(p=>`<option value="${escapeHtml(p)}">${escapeHtml(p)}</option>`).join("");if(phrases.includes(selected))trainingPhrase.value=selected}
function updateProgress(){const counts=engine.counts(),phrases=engine.phrases(),totalSamples=Object.values(counts).reduce((a,b)=>a+b,0),trainedPhrases=Object.values(counts).filter(n=>n>0).length;trainingCount.textContent=`${trainedPhrases}語 / ${totalSamples}回`;phraseProgress.innerHTML=phrases.map(p=>`<button class="progress-item ${counts[p]?"trained":""}" type="button" data-select-phrase="${escapeHtml(p)}"><strong>${escapeHtml(shortLabel(p))}</strong>${counts[p]} / 3</button>`).join("");phraseProgress.querySelectorAll("[data-select-phrase]").forEach(btn=>btn.addEventListener("click",()=>{trainingPhrase.value=btn.dataset.selectPhrase;trainingPhrase.scrollIntoView({behavior:"smooth",block:"center"})}));recognizeButton.disabled=!cameraStarted||trainedPhrases<2||busy}
function formatProfile(profile,state){if(!profile)return"まだ本人プロファイルはありません。指定文を1本登録すると、ここに口の動きの基準が表示されます。";const status=state.done?"基礎キャリブレーション完了":`基礎データ収集中（${state.completed}/${state.total}）`;return `<strong>${status}</strong><div class="profile-metrics"><span>平均口開き <b>${profile.averageInnerOpening}</b></span><span>口開き幅 <b>${profile.averageOpeningRange}</b></span><span>横幅比 <b>${profile.averageWidthRatio}</b></span><span>動き量 <b>${profile.averageMotion}</b></span></div><small>${profile.sampleCount}本の指定文から算出。動画ではなく数値特徴を保存しています。</small>`}
function renderCalibration(){const prompts=engine.calibrationPrompts(),state=engine.calibrationState(),profile=engine.calibrationProfile();calibrationIndex=Math.max(0,Math.min(prompts.length-1,calibrationIndex));const prompt=prompts[calibrationIndex];calibrationCount.textContent=`${state.completed} / ${state.total}`;calibrationFill.style.width=`${Math.round(state.completed/state.total*100)}%`;calibrationPromptNumber.textContent=`${calibrationIndex+1} / ${prompts.length}`;calibrationPromptText.textContent=prompt;calibrationPrev.disabled=calibrationIndex<=0||busy;calibrationNext.disabled=calibrationIndex>=prompts.length-1||busy;calibrationCapture.disabled=!cameraStarted||!engineReady||busy;calibrationCapture.textContent=state.samples[prompt]?"この文章をもう一度登録する（約5秒）":"この文章を口パクで登録（約5秒）";calibrationProfile.innerHTML=formatProfile(profile,state);calibrationPromptList.innerHTML=prompts.map((item,index)=>`<button class="cal-dot ${state.samples[item]?"done":""} ${index===calibrationIndex?"current":""}" type="button" data-cal-index="${index}" aria-label="${index+1}番目 ${state.samples[item]?"登録済み":"未登録"}">${index+1}</button>`).join("");calibrationPromptList.querySelectorAll("[data-cal-index]").forEach(btn=>btn.addEventListener("click",()=>{if(busy)return;calibrationIndex=Number(btn.dataset.calIndex);renderCalibration()}))}
function moveToNextIncomplete(){const prompts=engine.calibrationPrompts(),state=engine.calibrationState();for(let offset=1;offset<=prompts.length;offset++){const idx=(calibrationIndex+offset)%prompts.length;if(!state.samples[prompts[idx]]){calibrationIndex=idx;return}}calibrationIndex=Math.min(calibrationIndex+1,prompts.length-1)}
function setBusy(value,badgeText="口パク記録中"){busy=value;recordingBadge.textContent=badgeText;recordingBadge.classList.toggle("hidden",!value);trainButton.disabled=!cameraStarted||!engineReady||value;calibrationCapture.disabled=!cameraStarted||!engineReady||value;startCamera.disabled=cameraStarted||value;stopCamera.disabled=!cameraStarted||value;addPhrase.disabled=value;updateProgress();renderCalibration()}
function pushConversationSnapshot(){conversationHistory.push(conversationText.value);if(conversationHistory.length>30)conversationHistory=conversationHistory.slice(-30);updateConversationButtons()}
const isSentenceEnding=text=>/(?:です|ます|ません|ください|でした|ました|ありがとう|大丈夫|わかりません|痛い|苦しい)[。！？!?]?$/.test(text.trim());
function appendToConversation(phrase){const unit=String(phrase||"").trim();if(!unit)return;pushConversationSnapshot();const current=conversationText.value.trimEnd();conversationText.value=!current?unit:`${current}${!/[。！？!?]$/.test(current)&&isSentenceEnding(current)?"。":""}${unit}`;conversationText.focus();conversationText.setSelectionRange(conversationText.value.length,conversationText.value.length);updateConversationButtons();cameraHint.textContent="文章に追加しました。続けて「口パクを読み取る」を押すと、次の言葉を足せます。"}
function updateConversationButtons(){const hasText=Boolean(conversationText.value.trim());undoConversation.disabled=conversationHistory.length===0;addPeriod.disabled=!hasText;clearConversation.disabled=!hasText;speakConversation.disabled=!hasText}
async function initialize(){renderPhraseOptions();renderCalibration();engineReady=await engine.init();const prompts=engine.calibrationPrompts(),state=engine.calibrationState(),firstIncomplete=prompts.findIndex(p=>!state.samples[p]);calibrationIndex=firstIncomplete>=0?firstIncomplete:0;updateProgress();renderCalibration();updateConversationButtons();if(!engineReady)cameraHint.textContent="読唇AIの読み込みに失敗しました。通信状態を確認して再読み込みしてください。読み上げ機能は利用できます。"}
startCamera.addEventListener("click",async()=>{try{startCamera.disabled=true;setStatus("カメラ起動中");await engine.startCamera();cameraStarted=true;cameraPlaceholder.classList.add("hidden");stopCamera.disabled=false;trainButton.disabled=!engineReady;calibrationCapture.disabled=!engineReady;setStatus(engineReady?"認識準備OK":"カメラのみ");updateProgress();renderCalibration()}catch(error){console.error(error);startCamera.disabled=false;setStatus("カメラ失敗");cameraHint.textContent=error.message||"カメラを開始できませんでした。"}});
stopCamera.addEventListener("click",()=>{engine.stopCamera();cameraStarted=false;cameraPlaceholder.classList.remove("hidden");startCamera.disabled=false;stopCamera.disabled=true;trainButton.disabled=true;calibrationCapture.disabled=true;recognizeButton.disabled=true;setStatus(engineReady?"AI準備OK":"AI読込失敗");renderCalibration()});
calibrationPrev.addEventListener("click",()=>{if(busy||calibrationIndex<=0)return;calibrationIndex--;renderCalibration()});
calibrationNext.addEventListener("click",()=>{const prompts=engine.calibrationPrompts();if(busy||calibrationIndex>=prompts.length-1)return;calibrationIndex++;renderCalibration()});
calibrationCapture.addEventListener("click",async()=>{if(busy)return;const prompts=engine.calibrationPrompts(),prompt=prompts[calibrationIndex];try{setBusy(true,"キャリブレーション準備");cameraHint.textContent=`まもなく開始します。「${prompt}」を声を出さず自然に口パクしてください。`;await sleep(700);recordingBadge.textContent=`指定文 ${calibrationIndex+1} を記録中`;const sample=await engine.captureCalibration(5200);engine.saveCalibrationSample(prompt,sample);cameraHint.textContent=`「${prompt}」を本人プロファイルへ登録しました。`;moveToNextIncomplete()}catch(error){alert(error.message||"キャリブレーションに失敗しました。")}finally{setBusy(false);renderCalibration()}});
calibrationReset.addEventListener("click",()=>{if(!confirm("指定文から作った本人キャリブレーションデータをすべて削除しますか？登録語の学習データは消えません。"))return;engine.clearCalibration();calibrationIndex=0;renderCalibration();cameraHint.textContent="キャリブレーションをリセットしました。1番目の指定文から登録できます。"});
addPhrase.addEventListener("click",()=>{try{const phrase=engine.ensurePhrase(customPhrase.value);renderPhraseOptions(phrase);customPhrase.value="";updateProgress();cameraHint.textContent=`「${phrase}」を追加しました。次に口パクを3回ほど登録してください。`}catch(error){alert(error.message||"言葉を追加できませんでした。")}});customPhrase.addEventListener("keydown",e=>{if(e.key==="Enter"){e.preventDefault();addPhrase.click()}});
trainButton.addEventListener("click",async()=>{if(busy)return;const phrase=trainingPhrase.value;try{setBusy(true,`「${phrase}」を記録中`);cameraHint.textContent=`声を出さず「${phrase}」と自然に口を動かしてください。`;const seq=await engine.capture(2200);engine.addTemplate(phrase,seq);const count=engine.counts()[phrase]||0;cameraHint.textContent=`「${phrase}」を登録しました。あと${Math.max(0,3-count)}回が目安です。`}catch(error){alert(error.message||"登録に失敗しました。")}finally{setBusy(false);updateProgress()}});
recognizeButton.addEventListener("click",async()=>{if(busy)return;try{setBusy(true,"認識用の口パクを記録中");cameraHint.textContent="文章に足したい登録語を口パクしてください。";const seq=await engine.capture(2200),results=engine.classify(seq);renderCandidates(results);cameraHint.textContent="候補の「文章に追加」を押し、続けて次の口パクを入力できます。"}catch(error){alert(error.message||"認識に失敗しました。")}finally{setBusy(false)}});
function renderCandidates(results){candidateList.innerHTML="";recognitionEmpty.classList.toggle("hidden",results.length>0);if(!results.length){recognitionEmpty.textContent="学習データが不足しています。2つ以上の言葉を登録してください。";return}results.forEach((result,index)=>{const card=document.createElement("div");card.className="candidate-card";card.innerHTML=`<div class="candidate-copy"><strong>${index+1}. ${escapeHtml(result.phrase)}</strong><span>一致度目安 ${result.confidence}%</span></div><div class="candidate-actions"><button class="mini-btn mini-btn-primary" type="button" data-add-candidate>文章に追加</button><button class="mini-btn" type="button" data-speak-candidate>今すぐ発声</button></div>`;card.querySelector("[data-add-candidate]").addEventListener("click",()=>appendToConversation(result.phrase));card.querySelector("[data-speak-candidate]").addEventListener("click",()=>speak(result.phrase));candidateList.appendChild(card)})}
undoConversation.addEventListener("click",()=>{if(!conversationHistory.length)return;conversationText.value=conversationHistory.pop();updateConversationButtons()});addPeriod.addEventListener("click",()=>{if(!conversationText.value.trim())return;pushConversationSnapshot();conversationText.value=conversationText.value.trimEnd().replace(/[。！？!?]+$/,"")+"。";updateConversationButtons()});clearConversation.addEventListener("click",()=>{if(!conversationText.value.trim())return;pushConversationSnapshot();conversationText.value="";updateConversationButtons()});speakConversation.addEventListener("click",()=>speak(conversationText.value));conversationText.addEventListener("input",updateConversationButtons);
clearTraining.addEventListener("click",()=>{if(!confirm("端末内に保存した口パク学習データをすべて削除しますか？追加した言葉の一覧は残ります。"))return;engine.clearTemplates();candidateList.innerHTML="";recognitionEmpty.classList.remove("hidden");recognitionEmpty.textContent="学習後に口パクすると、ここに候補が表示されます。";updateProgress()});document.querySelectorAll("[data-speak]").forEach(button=>button.addEventListener("click",()=>speak(button.dataset.speak)));document.querySelectorAll("[data-append]").forEach(button=>button.addEventListener("click",()=>appendToConversation(button.dataset.append)));speakText.addEventListener("click",()=>speak(freeText.value));stopSpeak.addEventListener("click",()=>window.speechSynthesis?.cancel());if("serviceWorker" in navigator)navigator.serviceWorker.register("./sw.js").catch(error=>console.warn("SW registration failed",error));initialize();
